embeddings:
  tag: fasttext
  path: /home/andrei-cristian/projects/spam_detection/data/embeddings/fasttext_wiki_300_nsw.vec
model_name: lstm
model:
  rnn:
    max_seq_len: 128
    hyper:
      activation: relu
      bidirectional: True
      d_input: 300
      d_hidden: 32
      n_layers: 2
      p_dropout: 0.2
      learning_rate: 1.
      clip_value: .5
  lstm:
    max_seq_len: 128
    hyper:
      bidirectional: True
      d_input: 300
      d_hidden: 16
      n_layers: 1
      p_dropout: 0.3
      learning_rate: 1e-1
training:
  n_epochs: 50