data:
  preprocessed_path: data/processed/preprocessed_data.csv
  ignore_rare_words: True
  rare_words_threshold: 1
embeddings:
  used_embeddings: pretrained_fasttext
  pretrained_fasttext:
    path: /home/andrei-cristian/projects/spam_detection/data/embeddings/ft/cc.en.300.bin
    dimension: 100
model:
  used_model: lstm
  rnn:
    hyper:
      activation: relu
      bidirectional: True
      d_input: 100
      d_hidden: 32
      n_layers: 2
      p_dropout: 0.2
      learning_rate: 1.
      clip_value: .5
  lstm:
    hyper:
      bidirectional: True
      d_input: 100
      d_hidden: 32
      n_layers: 1
      p_dropout: 0.2
      learning_rate: 1e-3
training:
  n_epochs: 50