data:
  preprocessed_path: data/processed/preprocessed_data.csv
  ignore_rare_words: True
  rare_words_threshold: 1
embeddings:
  used_embeddings: pretrained_fasttext
  pretrained_fasttext:
    path: /home/andrei-cristian/projects/spam_detection/data/embeddings/ft/cc.en.300.bin
    dimension: 300
model:
  used_model: lstm
  rnn:
    hyper:
      activation: relu
      bidirectional: True
      d_input: 300
      d_hidden: 64
      n_layers: 3
      p_dropout: 0.25
      learning_rate: 1e-3
      clip_value: 2
  lstm:
    hyper:
      bidirectional: True
      d_input: 300
      d_hidden: 64
      n_layers: 3
      p_dropout: 0.25
      learning_rate: 1e-3
training:
  n_epochs: 50