data:
  preprocessed_path: data/processed/preprocessed_data.csv
  ignore_rare_words: True
  rare_words_threshold: 1
model:
  used_model: svc
  logistic:
    verbose: 1
    C: 10
    solver: liblinear
    multi_class: auto
    random_state: 21
    n_jobs: 4
    penalty: l2
    max_iter: 200
  svc:
    verbose: 0